<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheKameleon.Superpowers.Core\TheKameleon.Superpowers.Core.csproj" />
    <ProjectReference Include="..\TheKameleon.Superpowers.Bridge.Contracts\TheKameleon.Superpowers.Bridge.Contracts.csproj" />
  </ItemGroup>

</Project>
